package cn.wycode.githubuser.model;

/**
 * Created by wy
 * on 2017/2/23.
 */

public class Repo {
//    {
//        "id": 58181740,
//            "name": "AndroidBanner",
//            "full_name": "wangyucode/AndroidBanner",
//            "owner": {
//        "login": "wangyucode",
//                "id": 12728355,
//                "avatar_url": "https://avatars.githubusercontent.com/u/12728355?v=3",
//                "gravatar_id": "",
//                "url": "https://api.github.com/users/wangyucode",
//                "html_url": "https://github.com/wangyucode",
//                "followers_url": "https://api.github.com/users/wangyucode/followers",
//                "following_url": "https://api.github.com/users/wangyucode/following{/other_user}",
//                "gists_url": "https://api.github.com/users/wangyucode/gists{/gist_id}",
//                "starred_url": "https://api.github.com/users/wangyucode/starred{/owner}{/repo}",
//                "subscriptions_url": "https://api.github.com/users/wangyucode/subscriptions",
//                "organizations_url": "https://api.github.com/users/wangyucode/orgs",
//                "repos_url": "https://api.github.com/users/wangyucode/repos",
//                "events_url": "https://api.github.com/users/wangyucode/events{/privacy}",
//                "received_events_url": "https://api.github.com/users/wangyucode/received_events",
//                "type": "User",
//                "site_admin": false
//    },
//        "private": false,
//            "html_url": "https://github.com/wangyucode/AndroidBanner",
//            "description": "Banner滚动广告图View",
//            "fork": false,
//            "url": "https://api.github.com/repos/wangyucode/AndroidBanner",
//            "forks_url": "https://api.github.com/repos/wangyucode/AndroidBanner/forks",
//            "keys_url": "https://api.github.com/repos/wangyucode/AndroidBanner/keys{/key_id}",
//            "collaborators_url": "https://api.github.com/repos/wangyucode/AndroidBanner/collaborators{/collaborator}",
//            "teams_url": "https://api.github.com/repos/wangyucode/AndroidBanner/teams",
//            "hooks_url": "https://api.github.com/repos/wangyucode/AndroidBanner/hooks",
//            "issue_events_url": "https://api.github.com/repos/wangyucode/AndroidBanner/issues/events{/number}",
//            "events_url": "https://api.github.com/repos/wangyucode/AndroidBanner/events",
//            "assignees_url": "https://api.github.com/repos/wangyucode/AndroidBanner/assignees{/user}",
//            "branches_url": "https://api.github.com/repos/wangyucode/AndroidBanner/branches{/branch}",
//            "tags_url": "https://api.github.com/repos/wangyucode/AndroidBanner/tags",
//            "blobs_url": "https://api.github.com/repos/wangyucode/AndroidBanner/git/blobs{/sha}",
//            "git_tags_url": "https://api.github.com/repos/wangyucode/AndroidBanner/git/tags{/sha}",
//            "git_refs_url": "https://api.github.com/repos/wangyucode/AndroidBanner/git/refs{/sha}",
//            "trees_url": "https://api.github.com/repos/wangyucode/AndroidBanner/git/trees{/sha}",
//            "statuses_url": "https://api.github.com/repos/wangyucode/AndroidBanner/statuses/{sha}",
//            "languages_url": "https://api.github.com/repos/wangyucode/AndroidBanner/languages",
//            "stargazers_url": "https://api.github.com/repos/wangyucode/AndroidBanner/stargazers",
//            "contributors_url": "https://api.github.com/repos/wangyucode/AndroidBanner/contributors",
//            "subscribers_url": "https://api.github.com/repos/wangyucode/AndroidBanner/subscribers",
//            "subscription_url": "https://api.github.com/repos/wangyucode/AndroidBanner/subscription",
//            "commits_url": "https://api.github.com/repos/wangyucode/AndroidBanner/commits{/sha}",
//            "git_commits_url": "https://api.github.com/repos/wangyucode/AndroidBanner/git/commits{/sha}",
//            "comments_url": "https://api.github.com/repos/wangyucode/AndroidBanner/comments{/number}",
//            "issue_comment_url": "https://api.github.com/repos/wangyucode/AndroidBanner/issues/comments{/number}",
//            "contents_url": "https://api.github.com/repos/wangyucode/AndroidBanner/contents/{+path}",
//            "compare_url": "https://api.github.com/repos/wangyucode/AndroidBanner/compare/{base}...{head}",
//            "merges_url": "https://api.github.com/repos/wangyucode/AndroidBanner/merges",
//            "archive_url": "https://api.github.com/repos/wangyucode/AndroidBanner/{archive_format}{/ref}",
//            "downloads_url": "https://api.github.com/repos/wangyucode/AndroidBanner/downloads",
//            "issues_url": "https://api.github.com/repos/wangyucode/AndroidBanner/issues{/number}",
//            "pulls_url": "https://api.github.com/repos/wangyucode/AndroidBanner/pulls{/number}",
//            "milestones_url": "https://api.github.com/repos/wangyucode/AndroidBanner/milestones{/number}",
//            "notifications_url": "https://api.github.com/repos/wangyucode/AndroidBanner/notifications{?since,all,participating}",
//            "labels_url": "https://api.github.com/repos/wangyucode/AndroidBanner/labels{/name}",
//            "releases_url": "https://api.github.com/repos/wangyucode/AndroidBanner/releases{/id}",
//            "deployments_url": "https://api.github.com/repos/wangyucode/AndroidBanner/deployments",
//            "created_at": "2016-05-06T04:50:33Z",
//            "updated_at": "2016-05-06T04:50:56Z",
//            "pushed_at": "2016-05-06T04:50:55Z",
//            "git_url": "git://github.com/wangyucode/AndroidBanner.git",
//            "ssh_url": "git@github.com:wangyucode/AndroidBanner.git",
//            "clone_url": "https://github.com/wangyucode/AndroidBanner.git",
//            "svn_url": "https://github.com/wangyucode/AndroidBanner",
//            "homepage": null,
//            "size": 99,
//            "stargazers_count": 0,
//            "watchers_count": 0,
//            "language": "Java",
//            "has_issues": true,
//            "has_downloads": true,
//            "has_wiki": true,
//            "has_pages": false,
//            "forks_count": 0,
//            "mirror_url": null,
//            "open_issues_count": 0,
//            "forks": 0,
//            "open_issues": 0,
//            "watchers": 0,
//            "default_branch": "master"
//    }

    public String language;
}
